### ISSUE TITLE
Add support for non-literal array lengths

### ISSUE THREAD

**Issue by henridf** [ferranbt/fastssz#108]
The following example fails due to the array length not being a `*ast.BasicLit`.

```
package badone

const ArrayLength = 1

type S struct {
	Arr [ArrayLength]byte `ssz-size:"10"`
}
```

It would be handy to be able to support such cases (this is coming up when sszgen-annotating geth's Header struct).

**Comment by ferranbt** [comment]
I will try to get something rolling on this for this week.
