### ISSUE TITLE
panic: No files to generate

### ISSUE THREAD

**Issue by acswap** [ferranbt/fastssz#109]
![image](https://user-images.githubusercontent.com/89127078/190848335-279c8150-bf77-455b-a69e-6fa96ec9f1ee.png)
go version go1.19 linux/amd64

**Comment by ferranbt** [comment]
Sorry, this is not enough to reproduce the issue. I would recommend to use [go-eth-consensus](https://github.com/umbracle/go-eth-consensus) if you are looking for the `eth2` types with built-in ssz encodings.

**Comment by acswap** [comment]
Follow the instructions provided by Readme.md and wonder what went wrong
------- Original Message -------
2022年9月19日 星期一 2:30 下午，Ferran Borreguero ***@***.***> 来信：

**Comment by ferranbt** [comment]
I need more instructions/steps on how to reproduce this issue.
