### ISSUE TITLE
Cannot generate nested structs with ssz'able things from outside the current package.

### ISSUE THREAD

**Issue by itsdevbear** [ferranbt/fastssz#141]
`[ERR]: failed to encode FunBlock: could not find struct with name 'ExecutionPayloadCapella'`

<img width="540" alt="image" src="https://github.com/ferranbt/fastssz/assets/93690142/7c3056ed-4f15-4820-8432-7ec85ec4b298">

ExecutionPayloadCapella is very much indeed SSZ compataible

**Comment by ferranbt** [comment]
What is the `sszgen` command? Did you use the `--include` flag to include the `engine1` package?

**Comment by itsdevbear** [comment]
got it sorted @ferranbt
