### ISSUE TITLE
How does raw ssz list ser/dser?

### ISSUE THREAD

**Issue by fearlessfe** [ferranbt/fastssz#142]
I want to ser `TestList`, which is a ssz list
```
TestList [][]byte
```
But I must use a struct to wrap it as below
```
type TestStruct struct {
      TestList [][]byte
}
```
Because `TestStruct ` is a container, the ser result is `container offset` + `TestList `.

How can i get the ssz result of only `TestList `.

**Comment by GrapeBaBa** [comment]
same issue #135
