### ISSUE TITLE
`ssz.ExtendUint32` and `hh.AppendUint32` undefined error in the generated code

### ISSUE THREAD

**Issue by po-bera** [ferranbt/fastssz#148]
Hi,

I have the following struct and use `sszgen` to generate ssz code for it:
```
type Container struct {
	List []uint32 `ssz-max:"100"`
}
```
However, the generated code has two errors: 
- In `UnmarshalSSZ`: `undefined: ssz.ExtendUint32`
- In `HashTreeRootWith`: `hh.AppendUint32 undefined (type ssz.HashWalker has no field or method AppendUint32)`

Why does `fastssz` not support uint32 list?

**Comment by ferranbt** [comment]
> Why does fastssz not support uint32 list?

There was never a use case for that. The main goal for `sszgen` is to be fully compatible with the Ethereum consensus types for which there are available unit tests. 

Does #149 fixes your issue?

**Comment by po-bera** [comment]
Thanks for the answer @ferranbt. That makes sense.

#149 fixes the issue.
