### ISSUE TITLE
bug(generator): Generator cannot infer `ssz-size` for fixed length bytes.

### ISSUE THREAD

**Issue by itsdevbear** [ferranbt/fastssz#153]
This is a potential footgun as it will generate a valid type. However this type is treated as a composite.

Recommendation:
- Generator should either: a) error and force the user to supply `ssz-size:xx` or b) be able to infer the size.

<img width="622" alt="image" src="https://github.com/ferranbt/fastssz/assets/93690142/cb61ac26-5fe9-4cf6-9b51-81cb6d96760a">

![image](https://github.com/ferranbt/fastssz/assets/93690142/db748513-39fc-4eb0-8210-f8c3f729c4d5)

Testcase here: https://github.com/ferranbt/fastssz/pull/154

**Comment by ferranbt** [comment]
Does #155 fixes the issue?
