### ISSUE TITLE
If a struct tag exists, the generate doesn't implicitly recognize SSZ-able types

### ISSUE THREAD

**Issue by ocnc** [ferranbt/fastssz#156]
Prior to specifying my json tag, I was able to generate against a custom struct without specifiyng `ssz-size`. After adding a json tag, it no longer works

**Comment by ferranbt** [comment]
Hello, can you write a code snippet I can test?

**Comment by ferranbt** [comment]
I was able to reproduce this. This was introduced in #155. I have to refactor a little bit the part that handles the tags and the dimensions.
