### ISSUE TITLE
support custom marshal/unmarshal/hashroot

### ISSUE THREAD

**Issue by jshufro** [ferranbt/fastssz#161]
Similar to json custom marshaling and unmarshaling, if a type already defines receivers that make it a `Marshaler` and `Unmarshaler`, use those receivers when that type is encountered by the generator. 

This is particularly useful because fastssz doesn't provide a uint256 type, etc

e.g.:
```golang
type Foo struct {
  FieldOne Bar
}

type Bar struct {
  ssz.Unmarshaler
  ssz.Marshaler
  ssz.HashRoot
  ... unexported fields ...
}
```
sszgen should be able to create a serializer for `Foo` that calls `Bar.MarshalSSZTo` etc wherever appropriate.

**Comment by jshufro** [comment]
More specifically, it'd be great if i could import https://github.com/holiman/uint256

and then use `*uint256.Int` fields in a struct
and then generate ssz encoding for that struct

**Comment by ferranbt** [comment]
This feature is already available ([example](https://github.com/ferranbt/fastssz/blob/main/sszgen/testcases/other/case4.go#L5)).

**Comment by jshufro** [comment]
when trying to use the imported type i get:

```
$ ./gen.sh 
[ERR]: failed to encode SSZFile_v1: failed to encode TotalRewards: could not find struct with name 'Int'
```
where the struct has:
```golang
import "github.com/holiman/uint256"
type SSZFile_v1 struct {
  Test *uint256.Int
}
```

**Comment by jshufro** [comment]
Ah I just noticed that holiman's library doesn't implement `HashTreeRootWith` :cry:

**Comment by jshufro** [comment]
Managed to get it working with a wrapper. Holiman's `MarshalSSZTo` implementation is incompatible, interestingly, and I had to do some man-in-the-middle stuff.
