### ISSUE TITLE
tests v0.12.3 fail

### ISSUE THREAD

**Issue by alonmuroch** [ferranbt/fastssz#24]
=== RUN   TestSpecMinimal
    TestSpecMinimal: structs_test.go:263: ../eth2.0-spec-tests/tests/minimal/phase0/ssz_static/AggregateAndProof
    TestSpecMinimal: structs_test.go:263: ../eth2.0-spec-tests/tests/minimal/phase0/ssz_static/Attestation
    TestSpecMinimal: structs_test.go:263: ../eth2.0-spec-tests/tests/minimal/phase0/ssz_static/AttestationData
    TestSpecMinimal: structs_test.go:263: ../eth2.0-spec-tests/tests/minimal/phase0/ssz_static/AttesterSlashing
    TestSpecMinimal: structs_test.go:263: ../eth2.0-spec-tests/tests/minimal/phase0/ssz_static/BeaconBlock
    TestSpecMinimal: structs_test.go:299: list length is higher than max value
--- FAIL: TestSpecMinimal (0.35s)
=== RUN   TestSpecMainnet
    TestSpecMainnet: structs_test.go:284: ../eth2.0-spec-tests/tests/mainnet/phase0/ssz_static/AggregateAndProof
    TestSpecMainnet: structs_test.go:284: ../eth2.0-spec-tests/tests/mainnet/phase0/ssz_static/Attestation
    TestSpecMainnet: structs_test.go:284: ../eth2.0-spec-tests/tests/mainnet/phase0/ssz_static/AttestationData
    TestSpecMainnet: structs_test.go:284: ../eth2.0-spec-tests/tests/mainnet/phase0/ssz_static/AttesterSlashing
    TestSpecMainnet: structs_test.go:284: ../eth2.0-spec-tests/tests/mainnet/phase0/ssz_static/BeaconBlock
    TestSpecMainnet: structs_test.go:302: bad marshalling
--- FAIL: TestSpecMainnet (0.02s)
FAIL
FAIL	github.com/ferranbt/fastssz/spectests	0.640s
?   	github.com/ferranbt/fastssz/spectests/external	[no test files]
?   	github.com/ferranbt/fastssz/spectests/external2	[no test files]
FAIL

**Comment by ferranbt** [comment]
The test are done for the v0.10.0 spec, I would guess that some new fields have been included on the types. I do not work on my day to day on the beacon chain implementation so I do not follow protocol changes.

This project was made for the Prysm client. Usually, I fix things or implement new stuff when they need it so I would recommend you to go to their Discord channel and ask there. I think it will be enough including the missing fields.
