### ISSUE TITLE
Support for nested `List`

### ISSUE THREAD

**Issue by terencechain** [ferranbt/fastssz#40]
We'll need to support nested `List` for the upcoming `merge` milestone. Referencing the spec below, `transactions` in `BeaconBlockBody` is a nested  `List` which I don't think we have ever had it before. Can we please add support this?

```python
OpaqueTransaction: ByteList[MAX_BYTES_PER_OPAQUE_TRANSACTION]
transactions: List[OpaqueTransaction, MAX_EXECUTION_TRANSACTIONS]
```
https://github.com/ethereum/eth2.0-specs/blob/dev/specs/merge/beacon-chain.md#executionpayload

cc @ferranbt

**Comment by ferranbt** [comment]
Would not this be something like [MAX_EXECUTION_TRANSACTIONS][MAX_BYTES_PER_OPAQUE_TRANSACTION]byte which is already supported?

**Comment by rauljordan** [comment]
it would be something like `ssz-max: MAX_EXECUTION_TRANSACTIONS, MAX_BYTES_PER_OPAQUE_TRANSACTION` then. Does fastssz support this format for the tag?

**Comment by rauljordan** [comment]
Doesn't seem like
```go
type Transactions struct {
    Opaque [][]byte `json:"opaque" ssz-size"?,?" ssz-max:"2048,2048"`
}
```
is supported as we get:
`failed to encode Transactions: [][]byte expects a ssz-size tag`

**Comment by rauljordan** [comment]
Opened https://github.com/ferranbt/fastssz/pull/41/files, lemme know if this makes sense @ferranbt
