### ISSUE TITLE
HashTreeRoot does not work for BeaconState protos

### ISSUE THREAD

**Issue by prestonvanloon** [ferranbt/fastssz#67]
See: https://github.com/prysmaticlabs/prysm/pull/9402

Prysm's implementation of state hash tree root is defined here: https://github.com/prysmaticlabs/prysm/blob/53f70308715bb9d2f0a97c327becef9304daf890/beacon-chain/state/v1/state_trie.go#L201

The result of the generated ssz method (*BeaconState).HashTreeRoot() returns a different result. The Prysm implementation is known to work and passes spectests.

I do not know what the difference is between the two methods.

**Comment by ferranbt** [comment]
Is this mainnet or minimal tests?

**Comment by prestonvanloon** [comment]
@ferranbt So this specific test is one I have been investigating:

https://github.com/prysmaticlabs/prysm/blob/d6437a16eef58893403232ccaf6a9b9e81013149/beacon-chain/state/v2/state_trie_block_box_test.go#L121

`TestBeaconState_HashTreeRoot/different_slot` is giving different roots between the custom HTR and the generated HTR. We've found that that field 15 (PreviousEpochParticipation) is hashing different between the two. 

I've uploaded a test state in ssz format here. [testState.zip](https://github.com/ferranbt/fastssz/files/7866530/testState.zip)
This test state produces a root of `0xdda4d0fd854f9971c713d406a78dd835872a25209df0bbfc821134ed661e6be5` which I confirmed with [zcli](https://github.com/protolambda/zcli) and Prysm's custom hasher (see the above test [state_trie_block_box_test.go#121](https://github.com/prysmaticlabs/prysm/blob/d6437a16eef58893403232ccaf6a9b9e81013149/beacon-chain/state/v2/state_trie_block_box_test.go#L121)). fastssz returns the wrong root `0x38c3137a89e6d50411098f268a20e0628721cca819cc0e73a6439a3f98c92b37`

From my investigation, it seems like something off about the previous epoch participation but i'm not totally certain.

**Comment by prestonvanloon** [comment]
@ferranbt have you had a chance to review this issue? Thanks

**Comment by ferranbt** [comment]
I think this is already solved by #82
