### ISSUE TITLE
logarithm of 1 is 0 in any base

### ISSUE THREAD

**Issue by potuz** [ferranbt/fastssz#68]
This line in `getDepth` should change to return 0 when the argument is 1 https://github.com/ferranbt/fastssz/blob/master/hasher.go#L333

**Comment by ferranbt** [comment]
You are right, do you want to do a PR to fix it?

**Comment by potuz** [comment]
> You are right, do you want to do a PR to fix it?

Ooops forgot about this, opened a PR
