### ISSUE TITLE
sszgen: max size shadowed by first occurence of custom type def

### ISSUE THREAD

**Issue by lightclient** [ferranbt/fastssz#75]
```go
Bytes []byte

type A struct {
        Foo Bytes `ssz-max:"2048"`
}

type B struct {
        Bar Bytes `ssz-max:"32"`
}
```
If you run `sszgen` on these structs, both `A` and `B` will use `2048` as the max size for the byte list. In the case of `B`, this causes an incorrect hash-tree-root to be calculated, because the mix in should be based on `32`, not `2048.

**Comment by lightclient** [comment]
It's also making a `MarshalSSZ` method with an offset that is never used:
```
func (b *Bytes) MarshalSSZTo(buf []byte) (dst []byte, err error) {
    dst = buf
    offset := int(4)

    return
}
```

**Comment by lightclient** [comment]
@ferranbt I'm using the `sszgen` given by `go install github.com/ferranbt/fastssz/sszgen@latest`

**Comment by ferranbt** [comment]
Fixed in #76. There are two things here:
- There was an error indeed on the tags being reused for the other object. This one is fixed.
- The object `Bytes` cannot ever be ssz generated since it requires tags. You would have to skip it with `--exclude-objs` flag.

**Comment by lightclient** [comment]
Great - thank you @ferranbt. Will `--exclude-objs` also resolve the following issue:

```go
import "github.com/ethereum/go-ethereum/common/hexutil"

type A struct {
        Foo hexutil.Bytes `ssz-max:"2048"`
}

type B struct {
        Bar hexutil.Bytes `ssz-max:"32"`
}
```

and `sszgen --include ../go-ethereum/common/hexutil --path . --objs A,B` causes the resulting `encoding` file to have the error

```
./main_encoding.go:6:2: imported and not used: "github.com/ethereum/go-ethereum/common/hexutil"
```

**Comment by ferranbt** [comment]
Ok, now this is a different thing hahah. I was wondering if that `Bytes` object would come from a different place. In this case, you do not need to use `--exclude-objs` since it is not part of the main source. Do you mind opening another issue regarding this?
