### ISSUE TITLE
ssz.parseBitlist panics on empty byte array

### ISSUE THREAD

**Issue by prestonvanloon** [ferranbt/fastssz#9]
https://github.com/ferranbt/fastssz/blob/0b6e349af87af8ea2eb2bb5ce05fe4249530f571/hasher.go#L169

**Comment by ferranbt** [comment]
Isn't an empty bitlist invalid? As it is now, fastssz assumes that the higher levels of the application already handle the validity of the bitlist field for both marshal and htr.

**Comment by prestonvanloon** [comment]
True, but this library returns an error when a slice is not the appropriate length. I don't think a panic is the correct solution here

**Comment by ferranbt** [comment]
True, I'll work on a fix over the weekend.
